media:
  input: assets
  output: assets

content:
  - label: "Landing Page"
    type: page
    path: "index.html"
    fields:
      - label: "Content"
        name: "body"
        type: "rich-text"

  - label: "Work Detail"
    type: page
    path: "work-details.html"
    fields:
      - label: "Content"
        name: "body"
        type: "rich-text"
        
